server:
  port: 3344
spring:
  application:
    name: cloud-config-center   #注册进eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          username: fanchaojian
          password: 999520fcj
          uri: https://github.com/fanchaojian/springcloud_config.git
          ##搜索目录
          search-paths:
            - springcloud_config

      ###读取分支
      label: master

##注册到服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7003/eureka/
